// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tarifaAPI.Data;

#nullable disable

namespace tarifaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241101125123_TablaTarifas")]
    partial class TablaTarifas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("tarifaAPI.Models.Tarifa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DesdeFecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("DesdeTrabajadores")
                        .HasColumnType("int");

                    b.Property<DateTime>("HastaFecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("HastaTrabajadores")
                        .HasColumnType("int");

                    b.Property<float>("ImporteTrabajador")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("tarifas", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
